### ISSUE TITLE
Files blanked during liquid/gas refactor

### ISSUE THREAD

**Issue by claysmalley** [GlobalEnergyMonitor/GOIT-GGIT-pipeline-routes#3]
In commit 1f836cb, six files had their contents replaced with an empty, featureless GeoJSON:

* P0043
* P2689
* P6332
* P6488
* P6489
* P6490

These are all pipelines I mapped in the last week or so. Might this have been caused by invalid geometries?

**Comment by bairdlangenbrunner** [comment]
Thanks for flagging this @claysmalley, this was in part because of how the routes were marked in the database (if RouteAccuracy is blank or equal to "no route" for now, it fills in a blank entry). I noticed this happened and thought I corrected them; looking through now, all the routes are back in the repo except for P6488.

**Comment by bairdlangenbrunner** [comment]
I've now added the deleted contents from P6488.geojson to [c640c09](https://github.com/GlobalEnergyMonitor/GOIT-GGIT-pipeline-routes/commit/c640c09e0b16425e03a282d412e9d0327a340457), sorry about missing that and hopefully they're all looking like they're in place now.

**Comment by bairdlangenbrunner** [comment]
Hmm I'm actually realizing some of the metadata and attributes also get rewritten by the code I've used to rebuild this repository during commits. I'm going to revert a lot of these files to how they were when you uploaded them, sorry Clay for the confusion.

**Comment by bairdlangenbrunner** [comment]
Ok, I think all of the original metadata from your uploads should be back, Clay.

I may need to go through and edit a few to remove bad geometries, but otherwise I've checked all the files above and they are now properly in place. Will close this now but feel free to re-open if it looks awry still.
